language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
services:
- docker
env:
  global:
  - PINS="irmin-http:. irmin-fs:. irmin-git:. irmin-chunk:. irmin-mem:. irmin:. irmin-mirage:.
    irmin-unix:."
  - DISTRO="debian-stable"
  matrix:
  - PACKAGE="irmin-http" OCAML_VERSION="4.01.0"
  - PACKAGE="irmin-http" OCAML_VERSION="4.02.3"
  - PACKAGE="irmin-http" OCAML_VERSION="4.03.0"
  - PACKAGE="irmin-http" OCAML_VERSION="4.04.2"
  - PACKAGE="irmin-http" OCAML_VERSION="4.05.0"
  - PACKAGE="irmin-http" OCAML_VERSION="4.06.0"
  - PACKAGE="irmin-fs" OCAML_VERSION="4.03.0"
  - PACKAGE="irmin-fs" OCAML_VERSION="4.04.2"
  - PACKAGE="irmin-fs" OCAML_VERSION="4.05.0"
  - PACKAGE="irmin-fs" OCAML_VERSION="4.06.0"
  - PACKAGE="irmin-git" OCAML_VERSION="4.01.0"
  - PACKAGE="irmin-git" OCAML_VERSION="4.02.3"
  - PACKAGE="irmin-git" OCAML_VERSION="4.03.0"
  - PACKAGE="irmin-git" OCAML_VERSION="4.04.2"
  - PACKAGE="irmin-git" OCAML_VERSION="4.05.0"
  - PACKAGE="irmin-git" OCAML_VERSION="4.06.0"
  - PACKAGE="irmin-chunk" OCAML_VERSION="4.01.0"
  - PACKAGE="irmin-chunk" OCAML_VERSION="4.02.3"
  - PACKAGE="irmin-chunk" OCAML_VERSION="4.03.0"
  - PACKAGE="irmin-chunk" OCAML_VERSION="4.04.2"
  - PACKAGE="irmin-chunk" OCAML_VERSION="4.05.0"
  - PACKAGE="irmin-chunk" OCAML_VERSION="4.06.0"
  - PACKAGE="irmin-mem" OCAML_VERSION="4.03.0"
  - PACKAGE="irmin-mem" OCAML_VERSION="4.04.2"
  - PACKAGE="irmin-mem" OCAML_VERSION="4.05.0"
  - PACKAGE="irmin-mem" OCAML_VERSION="4.06.0"
  - PACKAGE="irmin" OCAML_VERSION="4.03.0"
  - PACKAGE="irmin" OCAML_VERSION="4.04.2"
  - PACKAGE="irmin" OCAML_VERSION="4.05.0"
  - PACKAGE="irmin" OCAML_VERSION="4.06.0"
  - PACKAGE="irmin-mirage" OCAML_VERSION="3.12.1"
  - PACKAGE="irmin-mirage" OCAML_VERSION="4.00.1"
  - PACKAGE="irmin-mirage" OCAML_VERSION="4.01.0"
  - PACKAGE="irmin-mirage" OCAML_VERSION="4.02.3"
  - PACKAGE="irmin-mirage" OCAML_VERSION="4.03.0"
  - PACKAGE="irmin-mirage" OCAML_VERSION="4.04.2"
  - PACKAGE="irmin-mirage" OCAML_VERSION="4.05.0"
  - PACKAGE="irmin-mirage" OCAML_VERSION="4.06.0"
  - PACKAGE="irmin-unix" OCAML_VERSION="4.01.0"
  - PACKAGE="irmin-unix" OCAML_VERSION="4.02.3"
  - PACKAGE="irmin-unix" OCAML_VERSION="4.03.0"
  - PACKAGE="irmin-unix" OCAML_VERSION="4.04.2"
  - PACKAGE="irmin-unix" OCAML_VERSION="4.05.0"
  - PACKAGE="irmin-unix" OCAML_VERSION="4.06.0"
